nginx:
  build: ./containers/nginx/
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app

php:
  build: ./containers/php/
  expose:
    - 9000
  volumes_from:
    - app

app:
  image: php:7-fpm
  volumes:
    - .:/var/www
  command: "true"

composer:
  image: composer/composer
  volumes:
    - .:/app

phpunit:
  image: phpunit/phpunit
  volumes:
   - .:/app
